@echo off
rem This file was generated by Fluent.  To kill Fluent and all its
rem related processes, run this script.  If Fluent exits normally
rem this file will be removed automatically.

set LOCALHOST=%COMPUTERNAME%
set REMOTE_SH="C:\PROGRA~1\ANSYSI~1\v191\fluent\\ntbin\\win64\\rsh.exe "
set KILL_CMD="C:\PROGRA~1\ANSYSI~1\v191\fluent\\ntbin\\win64\\winkill.exe "

echo Killing node process 52244...
if /i "%LOCALHOST%"=="ME03W0336LAB02" (%KILL_CMD% 52244) else (%REMOTE_SH% ME03W0336LAB02 %KILL_CMD% 52244)
echo Killing node process 17792...
if /i "%LOCALHOST%"=="ME03W0336LAB02" (%KILL_CMD% 17792) else (%REMOTE_SH% ME03W0336LAB02 %KILL_CMD% 17792)
echo Killing node process 42072...
if /i "%LOCALHOST%"=="ME03W0336LAB02" (%KILL_CMD% 42072) else (%REMOTE_SH% ME03W0336LAB02 %KILL_CMD% 42072)
echo Killing node process 17660...
if /i "%LOCALHOST%"=="ME03W0336LAB02" (%KILL_CMD% 17660) else (%REMOTE_SH% ME03W0336LAB02 %KILL_CMD% 17660)
echo Killing host process...
if /i "%LOCALHOST%"=="ME03W0336LAB02" (%KILL_CMD% 26204) else (%REMOTE_SH% ME03W0336LAB02 %KILL_CMD% 26204)
echo Killing cortex process...
if /i "%LOCALHOST%"=="ME03W0336LAB02" (%KILL_CMD% 39964) else (%REMOTE_SH% ME03W0336LAB02 %KILL_CMD% 39964)
del /q "C:\Users\mlanahan3\OneDrive - Georgia Institute of Technology\Desktop\repository\fluentpy\examples\batch\udf_test_files\\cleanup-fluent-ME03W0336LAB02-39964.bat"